### ISSUE TITLE
async_forward_entry_setup deprecated; replace with async_forward_entry_setups

### ISSUE THREAD

**Issue by philipflesher** [dwradcliffe/intellicenter#12]
Recent-ish versions of HA are reporting this for the integration setup now:

`Detected code that calls async_forward_entry_setup for integration, intellicenter with title: XXXXXX and entry_id: da350afdb366b09005bf81342d008d38, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.`

**Comment by dwradcliffe** [comment]
Duplicate of #8
