### ISSUE TITLE
Pentair Intellicenter Integration - Pool Light entity nonfunctional

### ISSUE THREAD

**Issue by atruest** [dwradcliffe/intellicenter#6]
Pentair Intellicenter integration work fine until a few days ago.
The "Pool Lights" entity stop working.  ALL other entities seem to work ok,
Rolled the Intellicenter SW back one version. Still same issue.
Deleted Integration and restarted several times with same results. 
Note: it appears via HA you can turn on the Lights but NO feedback and NO ability to turn off.
The Intellicenter application (iOS) works fine.
Core 2024.5.5
Super 2024.05.1
OS 12.3
Front  20240501.1

**Comment by atruest** [comment]
ThanksI am on 1.4.0a3 Intellicenter with the issue.On May 31, 2024, at 8:27 AM, Will ***@***.***> wrote:﻿
Had the same issue. I believe it's an issue with the latest (v1.5) release of the integration. I rolled back to v1.4 and lights are working for me again.

**Comment by atruest** [comment]
To clarify.I never had v1.5,   only V1.4.0a3Also , the intellicenter FW is 1.064 which works fine from the iOS app.Something changed recently that effected the light aspect of the integration.On May 31, 2024, at 9:06 AM, Tom Truesdell ***@***.***> wrote:﻿ThanksI am on 1.4.0a3 Intellicenter with the issue.On May 31, 2024, at 8:27 AM, Will ***@***.***> wrote:﻿
Had the same issue. I believe it's an issue with the latest (v1.5) release of the integration. I rolled back to v1.4 and lights are working for me again.

**Comment by xTerminatioNx** [comment]
> To clarify.I never had v1.5,   only V1.4.0a3Also , the intellicenter FW is 1.064 which works fine from the iOS app.Something changed recently that effected the light aspect of the integration.On May 31, 2024, at 9:06 AM, Tom Truesdell ***@***.***> wrote:﻿ThanksI am on 1.4.0a3 Intellicenter with the issue.On May 31, 2024, at 8:27 AM, Will ***@***.***> wrote:﻿ Had the same issue. I believe it's an issue with the latest (v1.5) release of the integration. I rolled back to v1.4 and lights are working for me again. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Sorry, v1.5 is the release name designated in the original repo but it still shows as v1.4.0a3 in HA. Pretty sure its mostly the same code. Some weird stuff going on in the various repos here. So whatever you want to call the new(er/est) version, v1.4.0 (non a3) is the integration version currently working with lights for me.

**Comment by atruest** [comment]
Thanks. UnderstoodCan you guide me to the 1.4.0 non a3 locstion in GH so I can roll back? I have never rolled an integration back but have read that I can find the older versions in GH.On May 31, 2024, at 1:33 PM, Will ***@***.***> wrote:﻿

To clarify.I never had v1.5,   only V1.4.0a3Also , the intellicenter FW is 1.064 which works fine from the iOS app.Something changed recently that effected the light aspect of the integration.On May 31, 2024, at 9:06 AM, Tom Truesdell @.> wrote:﻿ThanksI am on 1.4.0a3 Intellicenter with the issue.On May 31, 2024, at 8:27 AM, Will @.> wrote:﻿ Had the same issue. I believe it's an issue with the latest (v1.5) release of the integration. I rolled back to v1.4 and lights are working for me again. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***>

Sorry, v1.5 is the release name designated in the original repo but it still shows as v1.4.0a3 in HA. Pretty sure its mostly the same code. Some weird stuff going on in the various repos here. So whatever you want to call the new(er/est) version, v1.4.0 (non a3) is the integration version currently working with lights for me.

**Comment by xTerminatioNx** [comment]
> Thanks. UnderstoodCan you guide me to the 1.4.0 non a3 locstion in GH so I can roll back? I have never rolled an integration back but have read that I can find the older versions in GH.On May 31, 2024, at 1:33 PM, Will ***@***.***> wrote:﻿ To clarify.I never had v1.5,   only V1.4.0a3Also , the intellicenter FW is 1.064 which works fine from the iOS app.Something changed recently that effected the light aspect of the integration.On May 31, 2024, at 9:06 AM, Tom Truesdell @.> wrote:﻿ThanksI am on 1.4.0a3 Intellicenter with the issue.On May 31, 2024, at 8:27 AM, Will @.> wrote:﻿ Had the same issue. I believe it's an issue with the latest (v1.5) release of the integration. I rolled back to v1.4 and lights are working for me again. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***> Sorry, v1.5 is the release name designated in the original repo but it still shows as v1.4.0a3 in HA. Pretty sure its mostly the same code. Some weird stuff going on in the various repos here. So whatever you want to call the new(er/est) version, v1.4.0 (non a3) is the integration version currently working with lights for me. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Here is a direct link: https://github.com/jlvaillant/intellicenter/releases/tag/v1.4

However, if you are using HACS with the original repo (https://github.com/jlvaillant/intellicenter) then you can just go to the Intellicenter integration in HACS then click the three dots in the top right and choose "Redownload" and that will let you select a new version to download... so you would choose v1.4 from that dropdown and then click Download. Once its done I believe you will need to restart HA. You can check the integration version in HA to confirm it is using v.1.4.0 (non a3).

**Comment by atruest** [comment]
SweetThanks for your time and help.On May 31, 2024, at 1:45 PM, Will ***@***.***> wrote:﻿

Thanks. UnderstoodCan you guide me to the 1.4.0 non a3 locstion in GH so I can roll back? I have never rolled an integration back but have read that I can find the older versions in GH.On May 31, 2024, at 1:33 PM, Will @.> wrote:﻿ To clarify.I never had v1.5,   only V1.4.0a3Also , the intellicenter FW is 1.064 which works fine from the iOS app.Something changed recently that effected the light aspect of the integration.On May 31, 2024, at 9:06 AM, Tom Truesdell @.> wrote:﻿ThanksI am on 1.4.0a3 Intellicenter with the issue.On May 31, 2024, at 8:27 AM, Will @.> wrote:﻿ Had the same issue. I believe it's an issue with the latest (v1.5) release of the integration. I rolled back to v1.4 and lights are working for me again. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.> Sorry, v1.5 is the release name designated in the original repo but it still shows as v1.4.0a3 in HA. Pretty sure its mostly the same code. Some weird stuff going on in the various repos here. So whatever you want to call the new(er/est) version, v1.4.0 (non a3) is the integration version currently working with lights for me. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***>

Here is a direct link: https://github.com/jlvaillant/intellicenter/releases/tag/v1.4
However, if you are using HACS with the original repo (https://github.com/jlvaillant/intellicenter) then you can just go to the Intellicenter integration in HACS then click the three dots in the top right and choose "Redownload" and that will let you select a new version to download... so you would choose v1.4 from that dropdown and then click Download. Once its done I believe you will need to restart HA. You can check the integration version in HA to confirm it is using v.1.4.0 (non a3).

**Comment by atruest** [comment]
Worked like a charm! Thanks again.I am now verification for the developers that 1.4.0a3 has a bug.On May 31, 2024, at 2:13 PM, Tom Truesdell ***@***.***> wrote:﻿SweetThanks for your time and help.On May 31, 2024, at 1:45 PM, Will ***@***.***> wrote:﻿

Thanks. UnderstoodCan you guide me to the 1.4.0 non a3 locstion in GH so I can roll back? I have never rolled an integration back but have read that I can find the older versions in GH.On May 31, 2024, at 1:33 PM, Will @.> wrote:﻿ To clarify.I never had v1.5,   only V1.4.0a3Also , the intellicenter FW is 1.064 which works fine from the iOS app.Something changed recently that effected the light aspect of the integration.On May 31, 2024, at 9:06 AM, Tom Truesdell @.> wrote:﻿ThanksI am on 1.4.0a3 Intellicenter with the issue.On May 31, 2024, at 8:27 AM, Will @.> wrote:﻿ Had the same issue. I believe it's an issue with the latest (v1.5) release of the integration. I rolled back to v1.4 and lights are working for me again. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.> Sorry, v1.5 is the release name designated in the original repo but it still shows as v1.4.0a3 in HA. Pretty sure its mostly the same code. Some weird stuff going on in the various repos here. So whatever you want to call the new(er/est) version, v1.4.0 (non a3) is the integration version currently working with lights for me. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***>

Here is a direct link: https://github.com/jlvaillant/intellicenter/releases/tag/v1.4
However, if you are using HACS with the original repo (https://github.com/jlvaillant/intellicenter) then you can just go to the Intellicenter integration in HACS then click the three dots in the top right and choose "Redownload" and that will let you select a new version to download... so you would choose v1.4 from that dropdown and then click Download. Once its done I believe you will need to restart HA. You can check the integration version in HA to confirm it is using v.1.4.0 (non a3).

**Comment by dwradcliffe** [comment]
If you're up for testing something, try the latest code from my repo, and I think that already contains the fix.

**Comment by atruest** [comment]
Hi,Hope you don’t mind me asking a quick question. Just upgraded to 2025.1.0Had Pentair Intellicenter running fine under 1.4 not 1.5With the upgraded core Pentair dropped out. No lights , no pump and no extra circuits. Have some functionality (ie temp, etc)Decided to load 1.5 and got pump back but no lights and no extra circuits. Rolled back to 1.4 again and nothing like at 2025.1.0 core.Question.Did 1.5 ever get fixed for the lights issue?Has anyone commented yet on the 2025.1 causing Pentair issues? Probably too early yet.ThanksOn May 31, 2024, at 2:26 PM, Tom Truesdell ***@***.***> wrote:﻿Worked like a charm! Thanks again.I am now verification for the developers that 1.4.0a3 has a bug.On May 31, 2024, at 2:13 PM, Tom Truesdell ***@***.***> wrote:﻿SweetThanks for your time and help.On May 31, 2024, at 1:45 PM, Will ***@***.***> wrote:﻿

Thanks. UnderstoodCan you guide me to the 1.4.0 non a3 locstion in GH so I can roll back? I have never rolled an integration back but have read that I can find the older versions in GH.On May 31, 2024, at 1:33 PM, Will @.> wrote:﻿ To clarify.I never had v1.5,   only V1.4.0a3Also , the intellicenter FW is 1.064 which works fine from the iOS app.Something changed recently that effected the light aspect of the integration.On May 31, 2024, at 9:06 AM, Tom Truesdell @.> wrote:﻿ThanksI am on 1.4.0a3 Intellicenter with the issue.On May 31, 2024, at 8:27 AM, Will @.> wrote:﻿ Had the same issue. I believe it's an issue with the latest (v1.5) release of the integration. I rolled back to v1.4 and lights are working for me again. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.> Sorry, v1.5 is the release name designated in the original repo but it still shows as v1.4.0a3 in HA. Pretty sure its mostly the same code. Some weird stuff going on in the various repos here. So whatever you want to call the new(er/est) version, v1.4.0 (non a3) is the integration version currently working with lights for me. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***>

Here is a direct link: https://github.com/jlvaillant/intellicenter/releases/tag/v1.4
However, if you are using HACS with the original repo (https://github.com/jlvaillant/intellicenter) then you can just go to the Intellicenter integration in HACS then click the three dots in the top right and choose "Redownload" and that will let you select a new version to download... so you would choose v1.4 from that dropdown and then click Download. Once its done I believe you will need to restart HA. You can check the integration version in HA to confirm it is using v.1.4.0 (non a3).

**Comment by atruest** [comment]
Just a clarificationI did not see a non 1.4 non a3 version. So that’s probably why all light circuits are still not working as you stated many months ago. 1.5 = no lights (pool or extras)1.4.0a3= no lights (pool or extras)Can not find a straight 1.4 to roll to in HACs2025.1.0 core update takes out lights and pump. Ie was running 1.4.Hope that’s clearer. Do you recommend a ticket in GitHub?On Jan 3, 2025, at 4:57 PM, Tom Truesdell ***@***.***> wrote:﻿Hi,Hope you don’t mind me asking a quick question. Just upgraded to 2025.1.0Had Pentair Intellicenter running fine under 1.4 not 1.5With the upgraded core Pentair dropped out. No lights , no pump and no extra circuits. Have some functionality (ie temp, etc)Decided to load 1.5 and got pump back but no lights and no extra circuits. Rolled back to 1.4 again and nothing like at 2025.1.0 core.Question.Did 1.5 ever get fixed for the lights issue?Has anyone commented yet on the 2025.1 causing Pentair issues? Probably too early yet.ThanksOn May 31, 2024, at 2:26 PM, Tom Truesdell ***@***.***> wrote:﻿Worked like a charm! Thanks again.I am now verification for the developers that 1.4.0a3 has a bug.On May 31, 2024, at 2:13 PM, Tom Truesdell ***@***.***> wrote:﻿SweetThanks for your time and help.On May 31, 2024, at 1:45 PM, Will ***@***.***> wrote:﻿

Thanks. UnderstoodCan you guide me to the 1.4.0 non a3 locstion in GH so I can roll back? I have never rolled an integration back but have read that I can find the older versions in GH.On May 31, 2024, at 1:33 PM, Will @.> wrote:﻿ To clarify.I never had v1.5,   only V1.4.0a3Also , the intellicenter FW is 1.064 which works fine from the iOS app.Something changed recently that effected the light aspect of the integration.On May 31, 2024, at 9:06 AM, Tom Truesdell @.> wrote:﻿ThanksI am on 1.4.0a3 Intellicenter with the issue.On May 31, 2024, at 8:27 AM, Will @.> wrote:﻿ Had the same issue. I believe it's an issue with the latest (v1.5) release of the integration. I rolled back to v1.4 and lights are working for me again. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.> Sorry, v1.5 is the release name designated in the original repo but it still shows as v1.4.0a3 in HA. Pretty sure its mostly the same code. Some weird stuff going on in the various repos here. So whatever you want to call the new(er/est) version, v1.4.0 (non a3) is the integration version currently working with lights for me. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***>

Here is a direct link: https://github.com/jlvaillant/intellicenter/releases/tag/v1.4
However, if you are using HACS with the original repo (https://github.com/jlvaillant/intellicenter) then you can just go to the Intellicenter integration in HACS then click the three dots in the top right and choose "Redownload" and that will let you select a new version to download... so you would choose v1.4 from that dropdown and then click Download. Once its done I believe you will need to restart HA. You can check the integration version in HA to confirm it is using v.1.4.0 (non a3).
